import 'package:huge_basket/feature/home_screen/view_model/home_list_model.dart';



List<HomeListModel> storeList = [
  HomeListModel(
    title: "Walmart",
    category: "Grocery",
    address: "3456 Washington Street, US 4568",
    distance: "1 mile",
    rating: 4.5,
    image: "https://picsum.photos/200?1",
  ),
  HomeListModel(
    title: "Target",
    category: "Supermarket",
    address: "890 Main Street, US 2233",
    distance: "2 miles",
    rating: 4.3,
    image: "https://picsum.photos/200?2",
  ),
  HomeListModel(
    title: "Costco",
    category: "Wholesale",
    address: "678 Market Street, US 9987",
    distance: "3 miles",
    rating: 4.7,
    image: "https://picsum.photos/200?3",
  ),
  HomeListModel(
    title: "Kroger",
    category: "Grocery",
    address: "124 Hill Road, US 4521",
    distance: "2.5 miles",
    rating: 4.2,
    image: "https://picsum.photos/200?4",
  ),
  HomeListModel(
    title: "Whole Foods",
    category: "Organic Grocery",
    address: "99 Green Ave, US 1122",
    distance: "1.2 miles",
    rating: 4.6,
    image: "https://picsum.photos/200?5",
  ),
  HomeListModel(
    title: "7 Eleven",
    category: "Convenience",
    address: "11 Center Street, US 5566",
    distance: "0.5 mile",
    rating: 4.0,
    image: "https://picsum.photos/200?6",
  ),
  HomeListModel(
    title: "Best Buy",
    category: "Electronics",
    address: "23 Tech Road, US 7777",
    distance: "4 miles",
    rating: 4.4,
    image: "https://picsum.photos/200?7",
  ),
  HomeListModel(
    title: "Trader Joe's",
    category: "Grocery",
    address: "44 Market Lane, US 3322",
    distance: "1.8 miles",
    rating: 4.6,
    image: "https://picsum.photos/200?8",
  ),
  HomeListModel(
    title: "Safeway",
    category: "Supermarket",
    address: "123 River Road, US 6655",
    distance: "2.3 miles",
    rating: 4.1,
    image: "https://picsum.photos/200?9",
  ),
  HomeListModel(
    title: "Publix",
    category: "Grocery",
    address: "555 Lake Street, US 7788",
    distance: "3.1 miles",
    rating: 4.5,
    image: "https://picsum.photos/200?10",
  ),
  HomeListModel(
    title: "Aldi",
    category: "Discount Grocery",
    address: "89 Budget Lane, US 9001",
    distance: "2.7 miles",
    rating: 4.3,
    image: "https://picsum.photos/200?11",
  ),
  HomeListModel(
    title: "Lidl",
    category: "Supermarket",
    address: "78 Market Street, US 4433",
    distance: "3.5 miles",
    rating: 4.2,
    image: "https://picsum.photos/200?12",
  ),
  HomeListModel(
    title: "CVS",
    category: "Pharmacy",
    address: "321 Health Road, US 1212",
    distance: "1 mile",
    rating: 4.1,
    image: "https://picsum.photos/200?13",
  ),
  HomeListModel(
    title: "Walgreens",
    category: "Pharmacy",
    address: "456 Care Street, US 6767",
    distance: "1.4 miles",
    rating: 4.0,
    image: "https://picsum.photos/200?14",
  ),
  HomeListModel(
    title: "Dollar Tree",
    category: "Discount Store",
    address: "777 Cheap Lane, US 2323",
    distance: "2 miles",
    rating: 3.9,
    image: "https://picsum.photos/200?15",
  ),
  HomeListModel(
    title: "Home Depot",
    category: "Hardware",
    address: "88 Builder Road, US 9898",
    distance: "4.2 miles",
    rating: 4.4,
    image: "https://picsum.photos/200?16",
  ),
  HomeListModel(
    title: "IKEA",
    category: "Furniture",
    address: "12 Design Street, US 5567",
    distance: "5 miles",
    rating: 4.6,
    image: "https://picsum.photos/200?17",
  ),
  HomeListModel(
    title: "Staples",
    category: "Office Supplies",
    address: "67 Work Ave, US 7878",
    distance: "3 miles",
    rating: 4.2,
    image: "https://picsum.photos/200?18",
  ),
  HomeListModel(
    title: "PetSmart",
    category: "Pet Store",
    address: "45 Animal Street, US 9090",
    distance: "2.9 miles",
    rating: 4.5,
    image: "https://picsum.photos/200?19",
  ),
  HomeListModel(
    title: "GameStop",
    category: "Gaming",
    address: "66 Gamer Road, US 1111",
    distance: "1.7 miles",
    rating: 4.3,
    image: "https://picsum.photos/200?20",
  ),
];